// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: vjoltyamrcqgezvtpkse

class SupabaseConfig {
  static const String supabaseUrl = 'https://vjoltyamrcqgezvtpkse.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqb2x0eWFtcmNxZ2V6dnRwa3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTEwMjAsImV4cCI6MjA3ODAyNzAyMH0.I1mg_nfTfWnOzJkVKCUwfp45DK_AdFn8V38eumlAv2w';
}
